import type {
  AnalyticsOverviewData,
  AnalyticsRecentClick,
  AnalyticsPeriod,
} from "./types";

export const landingDummyOverviewData: AnalyticsOverviewData = {
  period: "7d",
  summary: {
    totalUrls: 24,
    totalClicks: 15420,
    clicksInPeriod: 2847,
    clicksToday: 423,
    clicksLast7d: 2847,
    clicksLast30d: 8934,
    activeLinksInPeriod: 18,
  },
  timeline: [
    { date: "2024-01-01", clicks: 312 },
    { date: "2024-01-02", clicks: 428 },
    { date: "2024-01-03", clicks: 389 },
    { date: "2024-01-04", clicks: 521 },
    { date: "2024-01-05", clicks: 467 },
    { date: "2024-01-06", clicks: 398 },
    { date: "2024-01-07", clicks: 332 },
  ],
  topLinks: [
    {
      shortCode: "promo24",
      clicks: 523,
      originalUrl: "https://example.com/special-promotion-2024",
      totalClicks: 2341,
      createdAt: "2023-12-15T10:30:00Z",
    },
    {
      shortCode: "blog1",
      clicks: 412,
      originalUrl: "https://example.com/blog/getting-started",
      totalClicks: 1892,
      createdAt: "2023-11-20T14:22:00Z",
    },
    {
      shortCode: "social",
      clicks: 387,
      originalUrl: "https://example.com/social-media-campaign",
      totalClicks: 1456,
      createdAt: "2024-01-02T09:15:00Z",
    },
    {
      shortCode: "news",
      clicks: 298,
      originalUrl: "https://example.com/news/latest-updates",
      totalClicks: 987,
      createdAt: "2023-12-28T16:45:00Z",
    },
    {
      shortCode: "event",
      clicks: 245,
      originalUrl: "https://example.com/events/january-webinar",
      totalClicks: 654,
      createdAt: "2024-01-05T11:00:00Z",
    },
  ],
  breakdowns: {
    deviceTypes: [
      { name: "Mobile", count: 1823 },
      { name: "Desktop", count: 876 },
      { name: "Tablet", count: 148 },
    ],
    browsers: [
      { name: "Chrome", count: 1456 },
      { name: "Safari", count: 789 },
      { name: "Firefox", count: 321 },
      { name: "Edge", count: 198 },
      { name: "Other", count: 83 },
    ],
    referrers: [
      { name: "Direct", count: 1234 },
      { name: "Twitter", count: 654 },
      { name: "LinkedIn", count: 432 },
      { name: "Google", count: 321 },
      { name: "Facebook", count: 206 },
    ],
    regions: [
      { name: "United States", count: 987 },
      { name: "United Kingdom", count: 456 },
      { name: "Germany", count: 321 },
      { name: "Canada", count: 287 },
      { name: "France", count: 198 },
    ],
  },
};

export const landingDummyRecentClicks: AnalyticsRecentClick[] = [
  {
    shortCode: "promo24",
    deviceType: "Mobile",
    browser: "Chrome",
    region: "United States",
    referrer: "Twitter",
    timeLabel: "2 min ago",
    clickedAt: "2024-01-07T14:30:00Z",
  },
  {
    shortCode: "blog1",
    deviceType: "Desktop",
    browser: "Safari",
    region: "United Kingdom",
    referrer: "Direct",
    timeLabel: "5 min ago",
    clickedAt: "2024-01-07T14:27:00Z",
  },
  {
    shortCode: "social",
    deviceType: "Mobile",
    browser: "Chrome",
    region: "Germany",
    referrer: "LinkedIn",
    timeLabel: "8 min ago",
    clickedAt: "2024-01-07T14:24:00Z",
  },
  {
    shortCode: "news",
    deviceType: "Tablet",
    browser: "Safari",
    region: "Canada",
    referrer: "Facebook",
    timeLabel: "12 min ago",
    clickedAt: "2024-01-07T14:20:00Z",
  },
  {
    shortCode: "promo24",
    deviceType: "Desktop",
    browser: "Chrome",
    region: "United States",
    referrer: "Direct",
    timeLabel: "15 min ago",
    clickedAt: "2024-01-07T14:17:00Z",
  },
];
