import type {
  AnalyticsLinkRow,
  AnalyticsOverviewData,
  AnalyticsPeriod,
  AnalyticsRecentClick,
  AnalyticsUrlDetail,
} from "./types";

export const MOCK_ANALYTICS_BY_PERIOD: Record<
  AnalyticsPeriod,
  AnalyticsOverviewData
> = {
  "7d": {
    period: "7d",
    summary: {
      totalUrls: 48,
      totalClicks: 5420,
      clicksInPeriod: 892,
      clicksToday: 124,
      clicksLast7d: 892,
      clicksLast30d: 2104,
      activeLinksInPeriod: 22,
    },
    timeline: [
      { date: "May 10", clicks: 98 },
      { date: "May 11", clicks: 112 },
      { date: "May 12", clicks: 134 },
      { date: "May 13", clicks: 121 },
      { date: "May 14", clicks: 156 },
      { date: "May 15", clicks: 147 },
      { date: "May 16", clicks: 124 },
    ],
    topLinks: [
      {
        shortCode: "k9Xm",
        clicks: 312,
        originalUrl: "https://acme.com/launch",
        totalClicks: 1840,
        createdAt: "2026-04-02T10:00:00.000Z",
      },
      {
        shortCode: "p2Qn",
        clicks: 198,
        originalUrl: "https://docs.example.com/guide",
        totalClicks: 920,
        createdAt: "2026-04-18T14:22:00.000Z",
      },
      {
        shortCode: "v7Rt",
        clicks: 156,
        originalUrl: "https://shop.brand.io/summer",
        totalClicks: 640,
        createdAt: "2026-05-01T09:15:00.000Z",
      },
      {
        shortCode: "m4Jk",
        clicks: 124,
        originalUrl: "https://blog.studio.dev/ship-faster",
        totalClicks: 410,
        createdAt: "2026-05-08T11:40:00.000Z",
      },
      {
        shortCode: "h8Wq",
        clicks: 98,
        originalUrl: "https://newsletter.io/subscribe",
        totalClicks: 355,
        createdAt: "2026-05-10T08:05:00.000Z",
      },
      {
        shortCode: "b3Ln",
        clicks: 87,
        originalUrl: "https://github.com/org/release",
        totalClicks: 290,
        createdAt: "2026-05-12T16:20:00.000Z",
      },
      {
        shortCode: "z1Pc",
        clicks: 72,
        originalUrl: "https://store.example.com/checkout",
        totalClicks: 220,
        createdAt: "2026-05-14T09:55:00.000Z",
      },
      {
        shortCode: "t6Yf",
        clicks: 64,
        originalUrl: "https://meet.example.com/demo",
        totalClicks: 188,
        createdAt: "2026-05-15T13:10:00.000Z",
      },
    ],
    breakdowns: {
      deviceTypes: [
        { name: "mobile", count: 482 },
        { name: "desktop", count: 318 },
        { name: "tablet", count: 92 },
      ],
      browsers: [
        { name: "Chrome", count: 510 },
        { name: "Safari", count: 214 },
        { name: "Firefox", count: 98 },
      ],
      referrers: [
        { name: "direct", count: 340 },
        { name: "twitter.com", count: 198 },
        { name: "google.com", count: 156 },
      ],
      regions: [
        { name: "US", count: 412 },
        { name: "GB", count: 168 },
        { name: "DE", count: 124 },
      ],
    },
  },
  "24h": {
    period: "24h",
    summary: {
      totalUrls: 48,
      totalClicks: 5420,
      clicksInPeriod: 124,
      clicksToday: 124,
      clicksLast7d: 892,
      clicksLast30d: 2104,
      activeLinksInPeriod: 9,
    },
    timeline: [
      { date: "00:00", clicks: 4 },
      { date: "04:00", clicks: 8 },
      { date: "08:00", clicks: 22 },
      { date: "12:00", clicks: 38 },
      { date: "16:00", clicks: 31 },
      { date: "20:00", clicks: 18 },
      { date: "Now", clicks: 3 },
    ],
    topLinks: [
      {
        shortCode: "k9Xm",
        clicks: 48,
        originalUrl: "https://acme.com/launch",
        totalClicks: 1840,
        createdAt: "2026-04-02T10:00:00.000Z",
      },
      {
        shortCode: "p2Qn",
        clicks: 32,
        originalUrl: "https://docs.example.com/guide",
        totalClicks: 920,
        createdAt: "2026-04-18T14:22:00.000Z",
      },
    ],
    breakdowns: {
      deviceTypes: [
        { name: "mobile", count: 72 },
        { name: "desktop", count: 44 },
        { name: "tablet", count: 8 },
      ],
      browsers: [
        { name: "Chrome", count: 68 },
        { name: "Safari", count: 34 },
        { name: "Firefox", count: 14 },
      ],
      referrers: [
        { name: "direct", count: 52 },
        { name: "twitter.com", count: 38 },
        { name: "google.com", count: 22 },
      ],
      regions: [
        { name: "US", count: 58 },
        { name: "GB", count: 24 },
        { name: "DE", count: 18 },
      ],
    },
  },
  "30d": {
    period: "30d",
    summary: {
      totalUrls: 48,
      totalClicks: 5420,
      clicksInPeriod: 2104,
      clicksToday: 124,
      clicksLast7d: 892,
      clicksLast30d: 2104,
      activeLinksInPeriod: 35,
    },
    timeline: [
      { date: "Apr 17", clicks: 48 },
      { date: "Apr 22", clicks: 62 },
      { date: "Apr 27", clicks: 71 },
      { date: "May 02", clicks: 88 },
      { date: "May 07", clicks: 94 },
      { date: "May 12", clicks: 102 },
      { date: "May 16", clicks: 124 },
    ],
    topLinks: [
      {
        shortCode: "k9Xm",
        clicks: 840,
        originalUrl: "https://acme.com/launch",
        totalClicks: 1840,
        createdAt: "2026-04-02T10:00:00.000Z",
      },
      {
        shortCode: "p2Qn",
        clicks: 512,
        originalUrl: "https://docs.example.com/guide",
        totalClicks: 920,
        createdAt: "2026-04-18T14:22:00.000Z",
      },
      {
        shortCode: "v7Rt",
        clicks: 398,
        originalUrl: "https://shop.brand.io/summer",
        totalClicks: 640,
        createdAt: "2026-05-01T09:15:00.000Z",
      },
    ],
    breakdowns: {
      deviceTypes: [
        { name: "mobile", count: 1180 },
        { name: "desktop", count: 780 },
        { name: "tablet", count: 144 },
      ],
      browsers: [
        { name: "Chrome", count: 1240 },
        { name: "Safari", count: 520 },
        { name: "Firefox", count: 210 },
      ],
      referrers: [
        { name: "direct", count: 820 },
        { name: "twitter.com", count: 480 },
        { name: "google.com", count: 390 },
      ],
      regions: [
        { name: "US", count: 980 },
        { name: "GB", count: 420 },
        { name: "DE", count: 310 },
      ],
    },
  },
};

export const MOCK_RECENT_CLICKS: AnalyticsRecentClick[] = [
  {
    shortCode: "k9Xm",
    deviceType: "mobile",
    browser: "Chrome",
    region: "US",
    referrer: "twitter.com",
    timeLabel: "2:32 PM",
    clickedAt: new Date(Date.now() - 3 * 60_000).toISOString(),
  },
  {
    shortCode: "p2Qn",
    deviceType: "desktop",
    browser: "Safari",
    region: "GB",
    referrer: "direct",
    timeLabel: "2:28 PM",
    clickedAt: new Date(Date.now() - 7 * 60_000).toISOString(),
  },
  {
    shortCode: "v7Rt",
    deviceType: "mobile",
    browser: "Chrome",
    region: "DE",
    referrer: "google.com",
    timeLabel: "2:19 PM",
    clickedAt: new Date(Date.now() - 16 * 60_000).toISOString(),
  },
  {
    shortCode: "m4Jk",
    deviceType: "tablet",
    browser: "Firefox",
    region: "CA",
    referrer: "linkedin.com",
    timeLabel: "2:11 PM",
    clickedAt: new Date(Date.now() - 24 * 60_000).toISOString(),
  },
  {
    shortCode: "h8Wq",
    deviceType: "desktop",
    browser: "Chrome",
    region: "US",
    referrer: "news.ycombinator.com",
    timeLabel: "2:04 PM",
    clickedAt: new Date(Date.now() - 31 * 60_000).toISOString(),
  },
  {
    shortCode: "b3Ln",
    deviceType: "mobile",
    browser: "Safari",
    region: "FR",
    referrer: "direct",
    timeLabel: "1:58 PM",
    clickedAt: new Date(Date.now() - 37 * 60_000).toISOString(),
  },
  {
    shortCode: "k9Xm",
    deviceType: "desktop",
    browser: "Edge",
    region: "US",
    referrer: "google.com",
    timeLabel: "1:42 PM",
    clickedAt: new Date(Date.now() - 53 * 60_000).toISOString(),
  },
  {
    shortCode: "z1Pc",
    deviceType: "mobile",
    browser: "Chrome",
    region: "AU",
    referrer: "instagram.com",
    timeLabel: "1:35 PM",
    clickedAt: new Date(Date.now() - 60 * 60_000).toISOString(),
  },
  {
    shortCode: "p2Qn",
    deviceType: "mobile",
    browser: "Chrome",
    region: "NL",
    referrer: "direct",
    timeLabel: "1:22 PM",
    clickedAt: new Date(Date.now() - 73 * 60_000).toISOString(),
  },
  {
    shortCode: "t6Yf",
    deviceType: "desktop",
    browser: "Firefox",
    region: "SE",
    referrer: "slack.com",
    timeLabel: "1:08 PM",
    clickedAt: new Date(Date.now() - 87 * 60_000).toISOString(),
  },
  {
    shortCode: "v7Rt",
    deviceType: "mobile",
    browser: "Safari",
    region: "IT",
    referrer: "facebook.com",
    timeLabel: "12:54 PM",
    clickedAt: new Date(Date.now() - 101 * 60_000).toISOString(),
  },
  {
    shortCode: "m4Jk",
    deviceType: "desktop",
    browser: "Chrome",
    region: "US",
    referrer: "producthunt.com",
    timeLabel: "12:41 PM",
    clickedAt: new Date(Date.now() - 114 * 60_000).toISOString(),
  },
];

export const MOCK_LIVE_CLICKS: AnalyticsRecentClick[] = [
  ...MOCK_RECENT_CLICKS,
  {
    shortCode: "h8Wq",
    deviceType: "mobile",
    browser: "Chrome",
    region: "BR",
    referrer: "whatsapp.com",
    timeLabel: "12:28 PM",
    clickedAt: new Date(Date.now() - 127 * 60_000).toISOString(),
  },
  {
    shortCode: "b3Ln",
    deviceType: "desktop",
    browser: "Safari",
    region: "JP",
    referrer: "github.com",
    timeLabel: "12:15 PM",
    clickedAt: new Date(Date.now() - 140 * 60_000).toISOString(),
  },
  {
    shortCode: "z1Pc",
    deviceType: "tablet",
    browser: "Chrome",
    region: "MX",
    referrer: "direct",
    timeLabel: "11:58 AM",
    clickedAt: new Date(Date.now() - 157 * 60_000).toISOString(),
  },
  {
    shortCode: "k9Xm",
    deviceType: "mobile",
    browser: "Chrome",
    region: "IN",
    referrer: "google.com",
    timeLabel: "11:44 AM",
    clickedAt: new Date(Date.now() - 171 * 60_000).toISOString(),
  },
  {
    shortCode: "t6Yf",
    deviceType: "mobile",
    browser: "Firefox",
    region: "ES",
    referrer: "twitter.com",
    timeLabel: "11:30 AM",
    clickedAt: new Date(Date.now() - 185 * 60_000).toISOString(),
  },
];

export const MOCK_LINKS_CATALOG: AnalyticsLinkRow[] = [
  {
    shortCode: "k9Xm",
    originalUrl: "https://acme.com/launch",
    clicks: 1840,
    createdAt: "2026-04-02T10:00:00.000Z",
    updatedAt: "2026-05-16T14:00:00.000Z",
  },
  {
    shortCode: "p2Qn",
    originalUrl: "https://docs.example.com/guide",
    clicks: 920,
    createdAt: "2026-04-18T14:22:00.000Z",
    updatedAt: "2026-05-16T13:40:00.000Z",
  },
  {
    shortCode: "v7Rt",
    originalUrl: "https://shop.brand.io/summer",
    clicks: 640,
    createdAt: "2026-05-01T09:15:00.000Z",
    updatedAt: "2026-05-16T12:10:00.000Z",
  },
  {
    shortCode: "m4Jk",
    originalUrl: "https://blog.studio.dev/ship-faster",
    clicks: 410,
    createdAt: "2026-05-08T11:40:00.000Z",
    updatedAt: "2026-05-15T18:22:00.000Z",
  },
  {
    shortCode: "h8Wq",
    originalUrl: "https://newsletter.io/subscribe",
    clicks: 355,
    createdAt: "2026-05-10T08:05:00.000Z",
    updatedAt: "2026-05-16T11:05:00.000Z",
  },
  {
    shortCode: "b3Ln",
    originalUrl: "https://github.com/org/release",
    clicks: 290,
    createdAt: "2026-05-12T16:20:00.000Z",
    updatedAt: "2026-05-16T10:30:00.000Z",
  },
  {
    shortCode: "z1Pc",
    originalUrl: "https://store.example.com/checkout",
    clicks: 220,
    createdAt: "2026-05-14T09:55:00.000Z",
    updatedAt: "2026-05-16T09:15:00.000Z",
  },
  {
    shortCode: "t6Yf",
    originalUrl: "https://meet.example.com/demo",
    clicks: 188,
    createdAt: "2026-05-15T13:10:00.000Z",
    updatedAt: "2026-05-16T08:45:00.000Z",
  },
  {
    shortCode: "r5Dx",
    originalUrl: "https://status.example.com",
    clicks: 142,
    createdAt: "2026-03-28T07:00:00.000Z",
    updatedAt: "2026-05-14T22:00:00.000Z",
  },
  {
    shortCode: "n2Hv",
    originalUrl: "https://app.example.com/onboarding",
    clicks: 118,
    createdAt: "2026-04-25T19:30:00.000Z",
    updatedAt: "2026-05-13T16:50:00.000Z",
  },
  {
    shortCode: "c8Fm",
    originalUrl: "https://pricing.example.com/teams",
    clicks: 96,
    createdAt: "2026-05-03T12:00:00.000Z",
    updatedAt: "2026-05-12T11:20:00.000Z",
  },
  {
    shortCode: "w4Gs",
    originalUrl: "https://changelog.example.com/v2",
    clicks: 74,
    createdAt: "2026-05-11T15:45:00.000Z",
    updatedAt: "2026-05-15T20:10:00.000Z",
  },
];

const linkBreakdowns = {
  deviceTypes: [
    { name: "mobile", count: 198 },
    { name: "desktop", count: 96 },
    { name: "tablet", count: 18 },
  ],
  browsers: [
    { name: "Chrome", count: 210 },
    { name: "Safari", count: 68 },
    { name: "Firefox", count: 24 },
  ],
  operatingSystems: [
    { name: "iOS", count: 112 },
    { name: "Windows", count: 78 },
    { name: "macOS", count: 54 },
    { name: "Android", count: 68 },
  ],
  referrers: [
    { name: "direct", count: 142 },
    { name: "twitter.com", count: 88 },
    { name: "google.com", count: 52 },
    { name: "linkedin.com", count: 30 },
  ],
  regions: [
    { name: "US", count: 168 },
    { name: "GB", count: 62 },
    { name: "DE", count: 44 },
    { name: "CA", count: 38 },
  ],
  cities: [
    { name: "New York", count: 72 },
    { name: "London", count: 48 },
    { name: "Berlin", count: 32 },
    { name: "San Francisco", count: 28 },
  ],
};

function buildUrlDetail(
  shortCode: string,
  originalUrl: string,
  totalClicks: number,
  period: AnalyticsPeriod,
  clicksInPeriod: number,
  timeline: { date: string; clicks: number }[],
): AnalyticsUrlDetail {
  return {
    period,
    url: {
      shortCode,
      originalUrl,
      shortUrl: `https://linky.dev/${shortCode}`,
      clicks: totalClicks,
      createdAt: "2026-04-02T10:00:00.000Z",
      updatedAt: new Date().toISOString(),
    },
    summary: { totalClicks, clicksInPeriod },
    timeline,
    breakdowns: linkBreakdowns,
  };
}

export const MOCK_URL_ANALYTICS: Record<
  string,
  Record<AnalyticsPeriod, AnalyticsUrlDetail>
> = {
  k9xm: {
    "7d": buildUrlDetail(
      "k9Xm",
      "https://acme.com/launch",
      1840,
      "7d",
      312,
      MOCK_ANALYTICS_BY_PERIOD["7d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.35),
      })),
    ),
    "24h": buildUrlDetail(
      "k9Xm",
      "https://acme.com/launch",
      1840,
      "24h",
      48,
      MOCK_ANALYTICS_BY_PERIOD["24h"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.4),
      })),
    ),
    "30d": buildUrlDetail(
      "k9Xm",
      "https://acme.com/launch",
      1840,
      "30d",
      840,
      MOCK_ANALYTICS_BY_PERIOD["30d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.4),
      })),
    ),
  },
  p2qn: {
    "7d": buildUrlDetail(
      "p2Qn",
      "https://docs.example.com/guide",
      920,
      "7d",
      198,
      MOCK_ANALYTICS_BY_PERIOD["7d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.22),
      })),
    ),
    "24h": buildUrlDetail(
      "p2Qn",
      "https://docs.example.com/guide",
      920,
      "24h",
      32,
      MOCK_ANALYTICS_BY_PERIOD["24h"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.28),
      })),
    ),
    "30d": buildUrlDetail(
      "p2Qn",
      "https://docs.example.com/guide",
      920,
      "30d",
      512,
      MOCK_ANALYTICS_BY_PERIOD["30d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.24),
      })),
    ),
  },
  v7rt: {
    "7d": buildUrlDetail(
      "v7Rt",
      "https://shop.brand.io/summer",
      640,
      "7d",
      156,
      MOCK_ANALYTICS_BY_PERIOD["7d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.18),
      })),
    ),
    "24h": buildUrlDetail("v7Rt", "https://shop.brand.io/summer", 640, "24h", 18, [
      { date: "08:00", clicks: 3 },
      { date: "12:00", clicks: 6 },
      { date: "16:00", clicks: 5 },
      { date: "20:00", clicks: 4 },
    ]),
    "30d": buildUrlDetail(
      "v7Rt",
      "https://shop.brand.io/summer",
      640,
      "30d",
      398,
      MOCK_ANALYTICS_BY_PERIOD["30d"].timeline.map((p) => ({
        ...p,
        clicks: Math.round(p.clicks * 0.19),
      })),
    ),
  },
};
